// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BPType", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TypeCode");

                    b.ToTable("BPTypes");

                    b.HasData(
                        new
                        {
                            TypeCode = "C",
                            TypeName = "Customer"
                        },
                        new
                        {
                            TypeCode = "V",
                            TypeName = "Vendor"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BusinessPartner", b =>
                {
                    b.Property<string>("BPCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("BPName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("BPType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("BPCode");

                    b.HasIndex("BPType");

                    b.ToTable("BusinessPartners");

                    b.HasData(
                        new
                        {
                            BPCode = "C0001",
                            Active = true,
                            BPName = "Customer 1",
                            BPType = "C"
                        },
                        new
                        {
                            BPCode = "C0002",
                            Active = false,
                            BPName = "Customer 2",
                            BPType = "C"
                        },
                        new
                        {
                            BPCode = "V0001",
                            Active = true,
                            BPName = "Vendor 1",
                            BPType = "V"
                        },
                        new
                        {
                            BPCode = "V0002",
                            Active = false,
                            BPName = "Vendor 2",
                            BPType = "V"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("ItemCode");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemCode = "Itm1",
                            Active = true,
                            ItemName = "Item 1"
                        },
                        new
                        {
                            ItemCode = "Itm2",
                            Active = true,
                            ItemName = "Item 2"
                        },
                        new
                        {
                            ItemCode = "Itm3",
                            Active = false,
                            ItemName = "Item 3"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Orders.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BPCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ID");

                    b.ToTable("Orders");

                    b.HasDiscriminator<string>("OrderType").HasValue("Order");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Orders.OrderLine", b =>
                {
                    b.Property<int>("LineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DocID")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("OrderLineType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(38,18)");

                    b.HasKey("LineID");

                    b.ToTable("OrderLines");

                    b.HasDiscriminator<string>("OrderLineType").HasValue("OrderLine");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Orders.SaleOrderLineComment", b =>
                {
                    b.Property<int>("CommentLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentLineID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocID")
                        .HasColumnType("int");

                    b.Property<int>("LineID")
                        .HasColumnType("int");

                    b.HasKey("CommentLineID");

                    b.HasIndex("DocID");

                    b.HasIndex("LineID");

                    b.ToTable("SaleOrderLineComments");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("ID");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            FullName = "User 1",
                            Password = "P1",
                            UserName = "U1"
                        },
                        new
                        {
                            ID = 2,
                            Active = false,
                            FullName = "User 2",
                            Password = "P2",
                            UserName = "U2"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Orders.PurchaseOrder", b =>
                {
                    b.HasBaseType("Domain.Entities.Orders.Order");

                    b.HasIndex("BPCode");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastUpdatedBy");

                    b.HasDiscriminator().HasValue("PurchaseOrder");
                });

            modelBuilder.Entity("Domain.Entities.Orders.SaleOrder", b =>
                {
                    b.HasBaseType("Domain.Entities.Orders.Order");

                    b.HasIndex("BPCode");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastUpdatedBy");

                    b.HasDiscriminator().HasValue("SaleOrder");
                });

            modelBuilder.Entity("Domain.Entities.Orders.PurchaseOrderLine", b =>
                {
                    b.HasBaseType("Domain.Entities.Orders.OrderLine");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocID");

                    b.HasIndex("ItemCode");

                    b.HasIndex("LastUpdatedBy");

                    b.HasDiscriminator().HasValue("PurchaseOrderLine");
                });

            modelBuilder.Entity("Domain.Entities.Orders.SaleOrderLine", b =>
                {
                    b.HasBaseType("Domain.Entities.Orders.OrderLine");

                    b.Property<int?>("PurchaseOrderID")
                        .HasColumnType("int");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocID");

                    b.HasIndex("ItemCode");

                    b.HasIndex("LastUpdatedBy");

                    b.HasIndex("PurchaseOrderID");

                    b.HasDiscriminator().HasValue("SaleOrderLine");
                });

            modelBuilder.Entity("Domain.Entities.BusinessPartner", b =>
                {
                    b.HasOne("Domain.Entities.BPType", "Type")
                        .WithMany("BusinessPartners")
                        .HasForeignKey("BPType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Entities.Orders.SaleOrderLineComment", b =>
                {
                    b.HasOne("Domain.Entities.Orders.SaleOrder", "SaleOrder")
                        .WithMany("Comments")
                        .HasForeignKey("DocID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Orders.SaleOrderLine", "Line")
                        .WithMany("Comments")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("Domain.Entities.Orders.PurchaseOrder", b =>
                {
                    b.HasOne("Domain.Entities.BusinessPartner", "BusinessPartner")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("BPCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany("CreatedPurchaseOrders")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Updater")
                        .WithMany("UpdatedPurchaseOrders")
                        .HasForeignKey("LastUpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusinessPartner");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Domain.Entities.Orders.SaleOrder", b =>
                {
                    b.HasOne("Domain.Entities.BusinessPartner", "BusinessPartner")
                        .WithMany("SaleOrders")
                        .HasForeignKey("BPCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany("CreatedSaleOrders")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Updater")
                        .WithMany("UpdatedSaleOrders")
                        .HasForeignKey("LastUpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusinessPartner");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Domain.Entities.Orders.PurchaseOrderLine", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany("CreatedPurchaseOrderLines")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Orders.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("DocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Item", "Item")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Updater")
                        .WithMany("UpdatedPurchaseOrderLines")
                        .HasForeignKey("LastUpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Domain.Entities.Orders.SaleOrderLine", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany("CreatedSaleOrderLines")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Orders.SaleOrder", "SaleOrder")
                        .WithMany("Lines")
                        .HasForeignKey("DocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Item", "Item")
                        .WithMany("SaleOrderLines")
                        .HasForeignKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Updater")
                        .WithMany("UpdatedSaleOrderLines")
                        .HasForeignKey("LastUpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Orders.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderID");

                    b.Navigation("Creator");

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("SaleOrder");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Domain.Entities.BPType", b =>
                {
                    b.Navigation("BusinessPartners");
                });

            modelBuilder.Entity("Domain.Entities.BusinessPartner", b =>
                {
                    b.Navigation("PurchaseOrders");

                    b.Navigation("SaleOrders");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.Navigation("PurchaseOrderLines");

                    b.Navigation("SaleOrderLines");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedPurchaseOrderLines");

                    b.Navigation("CreatedPurchaseOrders");

                    b.Navigation("CreatedSaleOrderLines");

                    b.Navigation("CreatedSaleOrders");

                    b.Navigation("UpdatedPurchaseOrderLines");

                    b.Navigation("UpdatedPurchaseOrders");

                    b.Navigation("UpdatedSaleOrderLines");

                    b.Navigation("UpdatedSaleOrders");
                });

            modelBuilder.Entity("Domain.Entities.Orders.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Entities.Orders.SaleOrder", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Entities.Orders.SaleOrderLine", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
